app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', [
	'as' => 'home',
	'uses' => 'HomeController@home'
	]);

//Para poder ejecutar migraciones en shared host
Route::get('/migrate', function() {
   Artisan::call('migrate', array('--force' => 'true'));
});

// Usuarios autenticados
Route::group(['before' => 'auth'], function () {

	Route::group(['before' => 'csrf'], function() {

		Route::post('/user/change-password', [
			'uses' => 'UserController@postChangePassword'
			]);

		Route::put('/user', [
			'as' => 'user.update',
			'uses' => 'UserController@update'
			]);

		Route::resource('contacto', 'ContactoController',
			['only' => ['store', 'update', 'destroy']]);	

	});

	Route::get('/user/logout', [
		'as' => 'user.logout',
		'uses' => 'UserController@getLogout'
		]);			

	Route::get('/user/change-password', [
		'as' => 'user.change-password',
		'uses' => 'UserController@getChangePassword'
		]);

	Route::get('/user/edit', [
		'as' => 'user.edit',
		'uses' => 'UserController@edit'
		]);

	Route::get('/contacto/{contacto}/delete', [
		'as' => 'contacto.delete',
		'uses' => 'ContactoController@delete'
		]);

	Route::resource('contacto', 'ContactoController',
		['except' => ['store', 'update', 'destroy']]);
});

// Usuarios no autenticados
Route::group(['before' => 'guest'], function() {

	Route::group(['before' => 'csrf'], function() {
		
		Route::post('/user/login', [
			'uses' => 'UserController@postLogin'
			]);

		Route::post('/user/reset', [
			'uses' => 'UserController@postReset'
			]);

		Route::resource('user', 'UserController', 
			['only' => ['store']]);
	});

	Route::get('/user/login', [
		'as' => 'user.login',
		'uses' => 'UserController@getLogin'
		]);

	Route::get('/user/login/fb', [
		'as' => 'login.fb',
		'uses' => 'UserController@loginFB'
		]);

	Route::get('/user/login/fb/callback', [
		'as' => 'login.fb.callback',
		'uses' => 'UserController@loginFBCallback'
		]);

	Route::get('/user/reset', [
		'as' => 'user.reset',
		'uses' => 'UserController@getReset'
		]);

	Route::resource('user', 'UserController',
		['only' => ['create']]);

});

/*
Route::resource('user', 'UserController',
	['except' => ['index']]);
*/

app/views/layout/base.blade.php
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title> 
	@section('titulo') 
	Agenda
	@show
	</title>
	<!-- Referencing Bootstrap CSS that is hosted locally -->
    {{ HTML::style('css/bootstrap.min.css') }}
    {{ HTML::style('css/bootstrap-theme.css') }}
    {{ HTML::style('css/custom.css') }}
</head>
<body>
	
	@include('layout.navigation')

	@if(Session::has('success'))
		<div class="alert alert-success alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert">
			<span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			{{ Session::get('success') }}
		</div>
	@endif
	@if(Session::has('error'))
		<div class="alert alert-danger alert-dismissible" role="alert">
  			<button type="button" class="close" data-dismiss="alert">
  			<span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  			<strong>Error!</strong> {{ Session::get('error') }}
		</div>
	@endif

	@section('encabezado')
	@show
	
	<div id="contenido" class="container">
		@section('contenido')
		@show
	</div>

	@section('pie')
		@include('layout.footer')
	@show

	{{ HTML::script('js/jquery.min.js') }}
    {{ HTML::script('js/bootstrap.min.js') }}
    @section('script')
    @show
</body>
</html>

app/views/layout/footer.blade.php
<footer>
  <div class="container">
  <div class="row">
    <div class="col-md-4">
      <ul class="nav nav-pills">
        <li class="active"><a href="#">Acerca de</a></li>
        <li><a href="#">Soporte</a></li>
        <li><a href="#">Política de privacidad</a></li>
      </ul>
    </div>
    <div class="col-md-4">
      <h3 class="text-right">Agenda 2.0</h3>
    </div>
    <div class="col-md-4">
      <p class="text-right">Napsoft &copy; 2014</p>
    </div>
  </div>
  </div>
</footer>

app/views/layout/header.blade.php
<div class="container-fluid">
{{--
<div class="jumbotron">
    <h1>Tu Guía Telefónica en la Nube</h1>
    <p>Registrate hoy totalmente gratis.</p>
    {{ link_to_route('user.create', 'Registro', [], ['class' => 'btn btn-primary btn-lg']) }}
</div>
--}}

 	<!-- Carousel
    ================================================== -->
	<div class="row-fluid">
	  <div class="span12">
	    <div id="myCarousel" class="carousel slide">
	      <!-- Indicators -->
      	  <ol class="carousel-indicators">
	        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
	        <li data-target="#myCarousel" data-slide-to="1"></li>
      	  </ol>
	      <div class="carousel-inner">
	        <div class="item active">
	          <img src="images/phone-book1.jpg" alt="">
	          <div class="container">
	            <div class="carousel-caption">
	          		<h4>Tu Guía Telefónica en la Nube</h4>
	    			<p>Registrate hoy totalmente gratis.</p>
	    			{{ link_to_route('user.create', 'Registro', [], ['class' => 'btn btn-primary btn-lg']) }}
	            </div>
	          </div>
	        </div>
	        <div class="item">
	          <img src="images/phone-book2.jpg" alt="">
	          <div class="container">
	            <div class="carousel-caption">
	          		<h4>Su Privacidad es Nuestra Prioridad</h4>
	    			<p>No revelamos ni proporcionamos información sensible a terceros.</p>
	    			
	            </div>
	          </div>
	        </div>
	      </div><!-- carousel-inner -->
	      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
	      	<span class="glyphicon glyphicon-chevron-left"></span></a>
  		  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
  		  	<span class="glyphicon glyphicon-chevron-right"></span></a>
	    </div><!-- /.carousel -->
	  </div>
	</div>
</div>

app/views/layout/navigation.blade.php
 <!-- Navbar -->
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Agenda</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li class="active"><a href="{{ route('home') }}">
				<span class="glyphicon glyphicon-home"></span> Inicio</a>
			</li>
        @if(Auth::check()) 
			<li> {{ link_to_route('contacto.index', 'Contactos') }} </li>
		@else
			<li> <a href="{{ route('user.create') }}">
        		<span class="glyphicon glyphicon-user"> Registro</span></a> 
        	</li>
		@endif
		</ul>
      	<ul class="nav navbar-nav navbar-right">
      	@if(Auth::check()) 
  			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					Bienvenido, {{ Auth::user()->nombre . ' ' . Auth::user()->apellidos }} 
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<li> {{ link_to_route('user.edit', 'Perfil ') }} </li>
					<li role='presentation' class="divider"></li>
					<li> {{ link_to_route('user.change-password', 'Cambiar Contraseña') }}</li>
				</ul>
			</li>
			<li>
			{{ Form::open(['route' => ['user.logout'], 'method' => 'GET', 'class' => 'navbar-form' ]) }}
    		{{ Form::submit('Salir', ['class' => 'btn btn-primary']) }}
    		{{ Form::close() }}	
			</li>
		@else
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					Usuario invitado
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<li> {{ link_to_route('user.reset', '¿Olvidaste tu contraseña?') }} </li>
				</ul>
			</li>
			<li>
			{{ Form::open(['route' => ['user.login'], 'method' => 'GET', 'class' => 'navbar-form' ]) }}
        	{{ Form::submit('Acceder', ['class' => 'btn btn-primary']) }}
        	{{ Form::close() }}
        	</li>
		@endif
		</ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>